name: build-embedNoRecord-apk

on: [push, pull_request]

jobs:
  build-embed-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt-hotspot
          java-version: 17
          cache: gradle

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install ninja-build cmake

      - name: Build APK (Embed NoRecord Release)
        run: ./gradlew assembleEmbedNoRecordRelease

      - name: Upload APK (Embed NoRecord Release)
        uses: actions/upload-artifact@v4
        with:
          name: love-android-embed.apk
          path: app/build/outputs/apk/embedNoRecord/release/app-embed-noRecord-release-unsigned.apk
